acronyms = {
    # Taylor Swift
    "PTB": ["Picture To Burn", "Taylor Swift"],
    "TOMG": ["Teardrops On My Guitar", "Taylor Swift"],
    "APITW": ["A Place In This World", "Taylor Swift"],
    "CAY": ["Cold As You", "Taylor Swift"],
    "TTWAS": ["Tied Together With A Smile", "Taylor Swift"],
    "SSN": ["Should've Said No", "Taylor Swift"],
    "IOMWIWY": ["I'm Only Me When I'm With You", "Taylor Swift"],
    "APGH": ["A Perfectly Good Heart", "Taylor Swift"],

    # Fearless (Taylor's Version)
    "YBWM": ["You Belong With Me", "Fearless (Taylor's Version)"],
    "TMV": ["Tell Me Why", "Fearless (Taylor's Version)"],
    "YNS": ["You're Not Sorry", "Fearless (Taylor's Version)"],
    "TWILY": ["The Way I Loved You", "Fearless (Taylor's Version)"],
    "F&A": ["Forever & Always", "Fearless (Taylor's Version)"],
    "TBD": ["The Best Day", "Fearless (Taylor's Version)"],
    "JTF": ["Jump Then Fall", "Fearless (Taylor's Version)"],
    "CIWTR": ["Come In With The Rain", "Fearless (Taylor's Version)"],
    "TOSOTD": ["The Other Side Of The Door", "Fearless (Taylor's Version)"],
    "TWAF": ["Today Was A Fairytale", "Fearless (Taylor's Version)"],
    "YAOM": ["You All Over Me (Taylor's Version) [From The Vault] [ft. Maren Morris]", "Fearless (Taylor's Version)"],
    "MPF": ["Mr. Perfectly Fine (Taylor's Version) [From The Vault]", "Fearless (Taylor's Version)"],
    "WWH": ["We Were Happy (Taylor's Version) [From The Vault]", "Fearless (Taylor's Version)"],
    "BBB": ["Bye Bye Baby (Taylor's Version) [From The Vault]", "Fearless (Taylor's Version)"],

    # Speak Now (Taylor's Version)
    "SN": ["Speak Now", "Speak Now (Taylor's Version)"],
    "BTD": ["Back To December", "Speak Now (Taylor's Version)"],
    "SOU": ["The Story of Us", "Speak Now (Taylor's Version)"],
    "TSOU": ["The Story of Us", "Speak Now (Taylor's Version)"],
    "NGU": ["Never Grow Up", "Speak Now (Taylor's Version)"],
    "BTR": ["Better Than Revenge", "Speak Now (Taylor's Version)"],
    "ETTVFTVFFOB": ["Electric Touch (Taylor's Version) (From The Vault) [ft. Fall Out Boy]",
                    "Speak Now (Taylor's Version)"],
    "ET": ["Electric Touch (Taylor's Version) (From The Vault) [ft. Fall Out Boy]", "Speak Now (Taylor's Version)"],
    "WEFILTVFTV": ["When Emma Falls in Love (Taylor's Version) (From The Vault)", "Speak Now (Taylor's Version)"],
    "WEFIL": ["When Emma Falls in Love (Taylor's Version) (From The Vault)", "Speak Now (Taylor's Version)"],
    "ICSUTVFTV": ["I Can See You (Taylor's Version) (From The Vault)", "Speak Now (Taylor's Version)"],
    "ICSU": ["I Can See You (Taylor's Version) (From The Vault)", "Speak Now (Taylor's Version)"],
    "ICSYTVFTV": ["I Can See You (Taylor's Version) (From The Vault)", "Speak Now (Taylor's Version)"],
    "ICSY": ["I Can See You (Taylor's Version) (From The Vault)", "Speak Now (Taylor's Version)"],
    "CCTVFTVFHW": ["Castles Crumbling (Taylor's Version) (From The Vault) [ft. Hayley Williams]",
                   "Speak Now (Taylor's Version)"],
    "CC": ["Castles Crumbling (Taylor's Version) (From The Vault) [ft. Hayley Williams]",
           "Speak Now (Taylor's Version)"],
    "FOTVFTV": ["Foolish One (Taylor's Version) (From The Vault)", "Speak Now (Taylor's Version)"],
    "FO": ["Foolish One (Taylor's Version) (From The Vault)", "Speak Now (Taylor's Version)"],

    # Red (Taylor's Version)
    "IKYWT": ["I Knew You Were Trouble", "Red (Taylor's Version)"],
    "ATWTMVTVFTV": ["All Too Well (10 Minute Version) [Taylor's Version] [From The Vault]", "Red (Taylor's Version)"],
    "ATWTMV": ["All Too Well (10 Minute Version)", "Red (Taylor's Version)"],
    "ATWSGAVRALPS": ["All Too Well (Sad Girl Autumn Version) [Recorded at Long Pond Studios]",
                     "Red (Taylor's Version)"],
    "ATWSGAV": ["All Too Well (Sad Girl Autumn Version) [Recorded at Long Pond Studios]", "Red (Taylor's Version)"],
    "ATW": ["All Too Well", "Red (Taylor's Version)"],
    "WANEGBT": ["We Are Never Ever Getting Back Together", "Red (Taylor's Version)"],
    "SSS": ["Stay Stay Stay", "Red (Taylor's Version)"],
    "TLT": ["The Last Time (Taylor's Version) [ft. Gary Lightbody]", "Red (Taylor's Version)"],
    "SBT": ["Sad Beautiful Tragic", "Red (Taylor's Version)"],
    "TLO": ["The Lucky One", "Red (Taylor's Version)"],
    "EHC": ["Everything Has Changed", "Red (Taylor's Version)"],
    "TMIK": ["The Moment I Knew", "Red (Taylor's Version)"],
    "CBBH": ["Come Back... Be Here", "Red (Taylor's Version)"],
    "GAH": ["Girl At Home", "Red (Taylor's Version)"],
    "SOG": ["State Of Grace", "Red (Taylor's Version)"],
    "MIAB": ["Message In a Bottle", "Red (Taylor's Version)"],
    "IBYTAM": ["I Bet You Think About Me", "Red (Taylor's Version)"],
    "TVFN": ["The Very First Night", "Red (Taylor's Version)"],

    # 1989 (Taylor's Version)
    "WTNY": ["Welcome To New York", "1989 (Taylor's Version)"],
    "OOTW": ["Out Of The Woods", "1989 (Taylor's Version)"],
    "AYHTDWS": ["All You Had To Do Was Stay", "1989 (Taylor's Version)"],
    "SIO": ["Shake It Off", "1989 (Taylor's Version)"],
    "IWYW": ["I Wish You Would", "1989 (Taylor's Version)"],
    "HYGTG": ["How You Get The Girl", "1989 (Taylor's Version)"],
    "IKP": ["I Know Places", "1989 (Taylor's Version)"],
    "YAIL": ["You Are In Love", "1989 (Taylor's Version)"],
    "SDG": ["Say Don't Go", "1989 (Taylor's Version)"],
    "NTWDT": ["Now That We Don't Talk", "1989 (Taylor's Version)"],
    "SL": ["Suburban Legends", "1989 (Taylor's Version)"],
    "IION": ["Is It Over Now?", "1989 (Taylor's Version)"],

    # reputation
    "RFI": ["Ready For It", "reputation"],
    "IDSB": ["I Did Something Bad", "reputation"],
    "DBM": ["Don't Blame Me", "reputation"],
    "LWYMMD": ["Look What You Made Me Do", "reputation"],
    "SIG": ["So It Goes...", "reputation"],
    "KOMH": ["King Of My Heart", "reputation"],
    "DWOHT": ["Dancing With Our Hands Tied", "reputation"],
    "TIWWCHNT": ["This Is Why We Can't Have Nice Things", "reputation"],
    "CIWYW": ["Call It What You Want", "reputation"],
    "NYD": ["New Year's Day", "reputation"],

    # Lover
    "IFTYE": ["I Forgot That You Existed", "Lover"],
    "ITHK": ["I Think He Knows", "Lover"],
    "MAATHP": ["Miss Americana & The Heartbreak Prince", "Lover"],
    "DBATC": ["Death By A Thousand Cuts", "Lover"],
    "SYGB": ["Soon You'll Get Better", "Lover"],
    "YNTCD": ["You Need To Calm Down", "Lover"],
    "INTHAF": ["It's Nice To Have A Friend", "Lover"],
    "AOTG": ["All Of The Girls", "Lover"],

    # folklore (deluxe version)
    "TLGAD": ["the last great american dynasty", "folklore (deluxe version)"],
    "MTR": ["my tears ricochet", "folklore (deluxe version)"],
    "TIMT": ["this is me trying", "folklore (deluxe version)"],

    # evermore (deluxe version)
    "TIDS": ["'tis the damn season", "evermore (deluxe version)"],
    "NBNC": ["no body, no crime (ft. HAIM)", "evermore (deluxe version)"],
    "CLM": ["cowboy like me", "evermore (deluxe version)"],
    "LSS": ["long story short", "evermore (deluxe version)"],
    "RWYLM": ["right where you left me", "evermore (deluxe version)"],
    "ITTG": ["it's time to go", "evermore (deluxe version)"],

    # Midnights (Til The Dawn Edition)
    "LH": ["Lavender Haze", "Midnights (3am Edition)"],
    "SOTB": ["Snow On The Beach (ft. Lana Del Rey)", "Midnights (3am Edition)"],
    "YOYOK": ["You're On Your Own, Kid", "Midnights (3am Edition)"],
    "TGW": ["The Great War", "Midnights (3am Edition)"],
    "BTTWS": ["Bigger Than The Whole Sky", "Midnights (3am Edition)"],
    "WCS": ["Would've, Could've, Should've", "Midnights (3am Edition)"],
    "YLM": ["You're Losing Me", "Midnights (3am Edition)"],

    # TTPD
    "TTPD": ["The Tortured Poets Department", "The Tortured Poets Department"],
    "MBOBHFT": ["My Boy Only Breaks His Favorite Toys", "The Tortured Poets Department"],
    "SLL": ["So Long, London", "The Tortured Poets Department"],
    "BDILH": ["But Daddy I Love Him", "The Tortured Poets Department"],
    "FOTS": ["Fresh Out The Slammer", "The Tortured Poets Department"],
    "GAS": ["Guilty As Sin?", "The Tortured Poets Department"],
    "WAOLOM": ["Who's Afraid Of Little Old Me?", "The Tortured Poets Department"],
    "ICFHNRIC": ["I Can Fix Him (No Really I Can)", "The Tortured Poets Department"],
    "ICDIWABH": ["I Can Do It With a Broken Heart", "The Tortured Poets Department"],
    "SMWEL": ["The Smallest Man Who Ever Lived", "The Tortured Poets Department"],
    "TSMWEL": ["The Smallest Man Who Ever Lived", "The Tortured Poets Department"],
    "IGGYB": ["imgonnagetyouback", "The Tortured Poets Department"],
    "CSSM": ["Chloe or Sam or Sophia or Marcus", "The Tortured Poets Department"],
    "COSOSOM": ["Chloe or Sam or Sophia or Marcus", "The Tortured Poets Department"],
    "HDIE": ["How Did It End?", "The Tortured Poets Department"],
    "SHS": ["So High School", "The Tortured Poets Department"],
    "IHIH": ["I Hate It Here", "The Tortured Poets Department"],
    "TYA": ["thanK you aIMee", "The Tortured Poets Department"],
    "ILIPW": ["I Look In People's Windows", "The Tortured Poets Department"],

    # Others
    "CTF": ["Christmas Tree Farm", "Singles"],
    "STF": ["Sweeter Than Fiction", "Singles"],
    "S&S": ["Safe & Sound (Taylor's Version)", "Singles"],
}

taylorsVersions = [
    "Fearless (Taylor's Version)",
    "Speak Now (Taylor's Version)",
    "Red (Taylor's Version)",
    "1989 (Taylor's Version)"
]
